<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>se.lnu</groupId>
    <artifactId>SCARF</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>SCARF</name>
    <description>SCARF</description>
    <url/>
    <licenses>
        <license>
            <name>GNU General Public License v3.0</name>
            <url>https://ww.gnu.org/licenses/gpl-3.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <developers>
        <developer>
            <id>sg</id>
            <name>Samuele Giussani</name>
            <email>samuele.giussani@lnu.se</email>
            <organization>Linnaeus University</organization>
            <organizationUrl>https://www.lnu.se</organizationUrl>
            <roles><role>Developer</role></roles>
        </developer>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
        <java.version>25</java.version>
        <lombok.version>1.18.40</lombok.version>
    </properties>
    <repositories>
        <repository>
            <id>local-dependencies</id>
            <url>file://${project.basedir}/local-dependencies/</url>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>

        <repository>
            <id>eclipse-modeling</id>
            <name>Eclipse Modeling Project Releases</name>
            <url>https://repo.eclipse.org/content/repositories/releases/</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- EMF -->
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.common</artifactId>
            <version>2.10.1.v20140901-1043</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore</artifactId>
            <version>2.10.1.v20140901-1043</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf</groupId>
            <artifactId>org.eclipse.emf.ecore.xmi</artifactId>
            <version>2.10.1.v20140901-1043</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.mapping</groupId>
            <artifactId>ecore2xml</artifactId>
            <version>2.3.0-v200706262000</version>
        </dependency>

        <!-- UML2 -->
        <dependency>
            <groupId>org.eclipse.core</groupId>
            <artifactId>runtime</artifactId>
            <version>3.10.0-v20140318-2214</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2</groupId>
            <artifactId>org.eclipse.uml2.uml</artifactId>
            <version>5.0.1.v20140910-1354</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.uml</groupId>
            <artifactId>resources</artifactId>
            <version>5.5.0.v20221116-1811</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2</groupId>
            <artifactId>org.eclipse.uml2.common</artifactId>
            <version>2.0.1.v20140910-1354</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2</groupId>
            <artifactId>org.eclipse.uml2.types</artifactId>
            <version>2.0.0.v20140910-1354</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.uml2.uml.profile</groupId>
            <artifactId>standard</artifactId>
            <version>1.5.0.v20221116-1811</version>
        </dependency>

        <!-- Acceleo -->
        <dependency>
            <groupId>org.eclipse.acceleo</groupId>
            <artifactId>org.eclipse.acceleo.engine</artifactId>
            <version>3.5.1.201409021433</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.acceleo</groupId>
            <artifactId>org.eclipse.acceleo.model</artifactId>
            <version>3.5.1.201409021433</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.acceleo</groupId>
            <artifactId>org.eclipse.acceleo.common</artifactId>
            <version>3.5.1.201409021433</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.acceleo</groupId>
            <artifactId>org.eclipse.acceleo.parser</artifactId>
            <version>3.5.1.201409021433</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.acceleo</groupId>
            <artifactId>lpg.runtime.java</artifactId>
            <version>2.0.17.v201004271640</version>
        </dependency>

        <!-- OCL -->
        <dependency>
            <groupId>org.eclipse.ocl</groupId>
            <artifactId>org.eclipse.ocl.ecore</artifactId>
            <version>3.3.100.v20140610-0641</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.ocl</groupId>
            <artifactId>org.eclipse.ocl</artifactId>
            <version>3.4.2.v20140725-2242</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.ocl</groupId>
            <artifactId>org.eclipse.ocl.common</artifactId>
            <version>1.2.0.v20140610-0641</version>
        </dependency>

        <!-- Guava -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.1.0-jre</version>
        </dependency>

        <!-- CloudSim Plus -->
        <dependency>
            <groupId>org.cloudsimplus</groupId>
            <artifactId>cloudsimplus</artifactId>
            <version>8.5.7</version>
        </dependency>

        <!-- Jackson -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.20.1</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>3.0-rc5</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.20.1</version>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.40</version>
            <scope>provided</scope>
        </dependency>

        <!-- TableSaw -->
        <dependency>
            <groupId>tech.tablesaw</groupId>
            <artifactId>tablesaw-core</artifactId>
            <version>0.43.1</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <name>scarf:${project.version}</name>
                        <env>
                            <BP_JVM_VERSION>25</BP_JVM_VERSION>
                            <BP_JVM_TYPE>JDK</BP_JVM_TYPE>
                        </env>
                    </image>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.15.0</version>
                <executions>
                    <execution>
                        <id>npm install</id>
                        <goals><goal>install-node-and-npm</goal></goals>
                        <configuration>
                            <nodeVersion>v20.11.1</nodeVersion>
                            <npmVersion>10.2.4</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm ci</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>ci --include=optional</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm build</id>
                        <goals><goal>npm</goal></goals>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.6.3</version>
                <executions>
                    <execution>
                        <id>emtl-generation</id>
                        <phase>process-classes</phase>
                        <goals><goal>java</goal></goals>
                        <configuration>
                            <mainClass>se.lnu.scarf.AcceleoCompiler</mainClass>
                            <classpathScope>compile</classpathScope>
                            <includeProjectDependencies>true</includeProjectDependencies>
                        </configuration>
                    </execution>
                    <execution>
                        <id>gci-dataset-generation</id>
                        <phase>process-classes</phase>
                        <goals><goal>java</goal></goals>
                        <configuration>
                            <mainClass>se.lnu.scarf.GridCarbonIntensityDataGenerator</mainClass>
                            <classpathScope>compile</classpathScope>
                            <includeProjectDependencies>true</includeProjectDependencies>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>25</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.40</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>templates/main.mtl</exclude>
                    <exclude>gci/**</exclude>
                    <exclude>static/css/input.css</exclude>
                </excludes>
            </resource>
        </resources>
    </build>

</project>
