spring.application.name=SCARF
server.port=9090
spring.main.log-startup-info=false
spring.lifecycle.timeout-per-shutdown-phase=2s
logging.level.root = INFO
logging.level.org.springframework=INFO
logging.level.org.thymeleaf = INFO
logging.level.reactor.netty = INFO
logging.level.org.apache.catalina = INFO
debug=false


